I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 126, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 126, in script
    e "You've created a new Ren'Py game."
  File "/home/ungasis/Downloads/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/ungasis/Downloads/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Linux-5.19.0-38-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
Happy 1st Anniv! 1.0
Sun Apr 16 15:25:25 2023
